### ISSUE TITLE
Not working on Colab

### ISSUE THREAD

**Issue by RAOMMA** [js-aguiar/wheat-object-detection#1]
Hello, This code is not suitable for google colab. I am working on wheat head detection as my term project in deep learning so if you have code suitable to run on colab please share that one too

**Comment by js-aguiar** [comment]
The structure is indeed a little dificult to format in a single notebook, especially with the custom libraries. I would recommend to check the notebooks page for this competition on kaggle; you can find some notebooks like [this one](https://www.kaggle.com/pestipeti/pytorch-starter-fasterrcnn-train) that uses FasterRCNN.
